name: Python package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CIBW_SKIP: "pp*-win*" # skip until https://github.com/supermihi/pytaglib/issues/110 is resolved
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: cache built taglib on Windows, where it's super slow
        uses: actions/cache@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          path: build/taglib
          key: taglib-windows-${{ hashFiles('build_taglib.py') }}
      - name: cache cibuildwheel stuff
        uses: actions/cache@v3
        if: ${{ runner.os == 'Linux' }}
        with:
          key: cibuildwheel-v2.12.1
          path: /home/runner/.cache/cibuildwheel
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: publish package pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
