name: Python package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      TAGLIB_HOME: taglib-install
      PYTAGLIB_CYTHONIZE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: cache built taglib on windows
        uses: actions/cache@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          path: ${{ env.TAGLIB_HOME }}
          # renew the cache when how taglib is built changes (e.g. version update)
          key: taglib-install-windows-${{ hashFiles('build_taglib_windows.py') }}
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build TagLib (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: python build_taglib_windows.py --install-dest=$Env:TAGLIB_HOME
      - name: Install TagLib (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get install -y libtag1-dev ; else brew install taglib ; fi
      - name: install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest Cython wheel
      - name: Build
        run: python setup.py build install
      - name: sdist
        if: ${{ runner.os == 'Linux' }}
        run: python setup.py sdist
      - name: bdist
        if: ${{ runner.os == 'Windows' }}
        run: python setup.py bdist_wheel
      - name: Test with pytest
        run: pytest
      - name: upload sdist
        uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Linux' }}
        with:
          name: dist
          path: dist
          retention-days: 5
      - name: upload wheel
        uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          name: dist
          path: dist
          retention-days: 5
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: publish package pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
