name: Python package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      TAGLIB_HOME: taglib-install
      PYTAGLIB_CYTHONIZE: 1
      CIBW_BEFORE_ALL_WINDOWS: ""
      CIBW_BEFORE_BUILD_WINDOWS: "python build_taglib.py --install-dest=taglib-install"
      CIBW_SKIP: "cp36-* cp37-*"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: publish package pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
